#!/usr/bin/env bash

# @see https://www.postgresql.org/docs/current/sql-createview.html
# ^ implicitly-created CTE's name cannot be schema-qualified.

set -e

VIEW_NAME=v_paths_optimal
VIEW_COMMENT='view of optimal paths records generated by checking existence of certain junction records'
USE_SCHEMA="${USE_SCHEMA:-$DEFAULT_DB}"
USE_DB="${USE_DB:-$DEFAULT_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$USE_DB" <<-EOSQL
  CREATE OR REPLACE VIEW $USE_SCHEMA.$VIEW_NAME as (
    select * from $USE_SCHEMA.paths p
    where exists (
      select * from $USE_SCHEMA.paths_actions pa
        where pa.path_name = p.name
    )
    and exists (
      select * from $USE_SCHEMA.paths_skills ps
        where ps.path_name = p.name
    )
  );

  comment on view $VIEW_NAME is '$VIEW_COMMENT';
EOSQL
