#!/usr/bin/env bash

# @see https://www.postgresql.org/docs/current/sql-createview.html
# ^ implicitly-created CTE's name cannot be schema-qualified.

set -e

VIEW_NAME=v_incentives_optimal
VIEW_COMMENT='view of optimal incentives records generated by checking existence of certain junction records'
USE_SCHEMA="${USE_SCHEMA:-$DEFAULT_DB}"
USE_DB="${USE_DB:-$DEFAULT_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$USE_DB" <<-EOSQL
  CREATE OR REPLACE VIEW $USE_SCHEMA.$VIEW_NAME as (
    select * from $USE_SCHEMA.incentives i
    where exists (
          select * from $USE_SCHEMA.paths_incentives pi
            where pi.incentive_name = i.name
        )
  );

  comment on view $VIEW_NAME is '$VIEW_COMMENT';
EOSQL
