#!/usr/bin/env bash

# @see https://www.postgresql.org/docs/current/sql-createview.html
# ^ implicitly-created CTE's name cannot be schema-qualified.

set -e

VIEW_NAME=v_disciplines_optimal
VIEW_COMMENT='view of optimal disciplines records generated by checking existence of certain junction records'
USE_SCHEMA="${USE_SCHEMA:-$DEFAULT_DB}"
USE_DB="${USE_DB:-$DEFAULT_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$USE_DB" <<-EOSQL
  CREATE OR REPLACE VIEW $USE_SCHEMA.$VIEW_NAME as (
    select * from $USE_SCHEMA.disciplines d
    where exists (
          select * from $USE_SCHEMA.paths_disciplines pd
            where pd.discipline_name = d.name
        )
  );

  comment on view $VIEW_NAME is '$VIEW_COMMENT';
EOSQL
