#!/usr/bin/env bash

# @see https://www.postgresql.org/docs/current/sql-createview.html
# ^ implicitly-created CTE's name cannot be schema-qualified.

set -e

VIEW_NAME=v_academias_optimal
VIEW_COMMENT='view of optimal academias records generated by checking existence of certain junction records'
USE_SCHEMA="${USE_SCHEMA:-$USE_SCHEMA}"
USE_DB="${USE_DB:-$USE_SCHEMA}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$USE_DB" <<-EOSQL
  CREATE OR REPLACE VIEW $USE_SCHEMA.$VIEW_NAME as (
    select * from $USE_SCHEMA.academias a
    where exists (
          select * from $USE_SCHEMA.paths_academias pa
            where pa.academia_name = a.name
        )
  );

  comment on view $VIEW_NAME is '$VIEW_COMMENT';
EOSQL
